spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: 'false'
    database: mysql
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: 'true'
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
