spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: 'false'
    database: mysql
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: 'true'
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MariaDB103Dialect

servlet:
  multipart:
    file-size-threshold: 1MB
    max-file-size: 100MB
    max-request-size: 100MB

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS}
      secretKey: ${AWS_SECRET}
    s3:
       bucket: ${AWS_BUCKET}
    region:
       static: ap-northeast-2
    stack:
       auto: false